version: '3.8'

services:
  jekyll:
    build: 
      context: ./services/jekyll
      dockerfile: Dockerfile
    volumes:
      - ./shared:/shared:ro
      - ./services/jekyll/_site:/srv/jekyll/_site
    environment:
      - JEKYLL_ENV=production
    networks:
      - web-network

  parser:
    build:
      context: ./services/parser
      dockerfile: Dockerfile
    volumes:
      - ./vault:/vault:ro
      - ./shared:/shared
    networks:
      - web-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/nginx/conf.d:/etc/nginx/conf.d
      - ./services/jekyll/_site:/usr/share/nginx/html
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - jekyll
    networks:
      - web-network

networks:
  web-network:
    driver: bridge 